// components/Vue.js/src/components/Palindrome.vue
<template>
  <div ref="canvas"></div>
</template>

<script>
import palindromeLib, { devPalindrome } from '../palindrome/palindrome.js';

export default {
  mounted() {
    const container = document.createElement('div');
    container.setAttribute('id', 'palindrome');
    
    const config = devPalindrome();
    this.applyConfiguration(this.config, config);
    config.data = this.dataStructure || {};

    palindromeLib(container, { ...config });
    this.$refs.canvas.appendChild(container);
  },
  methods: {
    applyConfiguration(userConfig, currentConfig) {
      for (const [key, value] of Object.entries(userConfig)) {
        currentConfig[key] = value;
      }
      return currentConfig;
    }
  },
  name: 'Palindrome-component',
  props: ['dataStructure', 'config']
}
</script>

// components/React.js/src/Palindrome.js
import React, { useRef, useEffect } from 'react';
import palindromeLib, { devPalindrome } from './palindrome/palindrome.js';

const Palindrome = (props) => {
  const canvasRef = useRef(null);

  const applyConfiguration = (userConfig, currentConfig) => {
    for (const [key, value] of Object.entries(userConfig)) {
      currentConfig[key] = value;
    }
    return currentConfig;
  };
  useEffect(() => {
    const container = document.createElement('div');
    container.setAttribute('id', 'palindrome');
    // eslint-disable-next-line 
    const config = devPalindrome();
    
    config.data = props.dataStructure ?? {};
    // applyConfiguration(props.config, config);
    
    palindromeLib(container, { ...config });
    canvasRef.current.appendChild(container);

    return () => {
      if (canvasRef.current) {
        // eslint-disable-next-line 
        setTimeout(() => {
          canvasRef.current.removeChild(container);
        }, 0);
      }
    };
  }, [props]);

  return (
    <>
      <div ref={canvasRef}></div>
    </>
  );
};

export default Palindrome;
