// components/React.js/src/App.js
import { useEffect, useState } from 'react';
import Palindrome from './Palindrome';
import { getData } from './useCaseExample';

function App() {
  const [dataStructure, setDataStructure] = useState({});
  const [config, setConfig] = useState({});

  useEffect(() => {
    const data = getData();
    setDataStructure(data);
    setConfig({
      displayGrid: false
    });
  }, []);

  return (
    <div className="App">
      <Palindrome dataStructure = {dataStructure} config = {config} />
    </div>
  );
}

export default App;

// components/Vue.js/src/App.vue
<template>
  <div id="app">
    <Palindrome :dataStructure="dataStructure" :config="config"/>
  </div>
</template>

<script>
import Palindrome from './components/Palindrome.vue'
import { getData } from './useCaseExample';
export default {
  name: 'App',
  components: {
    Palindrome
  },
  data() {
    const config = {displayGrid: false};
    return {
      dataStructure: getData(),
      config
    }
  }
}
</script>
